### Import torch as t

In [1]:
import torch as t

### Creating empty tensors

In [2]:
x = t.tensor([]) #Empty tensor
print(x)

x = t.empty(1) #Empty tensor of size 1 - scalar
print(x)

x = t.empty(3) #Empty tensor of size 3 - vector of size 3
print(x)

x = t.empty(2,3) #Empty 2D tensor of size 2 by 3
print(x) 

tensor([])
tensor([-1.3642e-19])
tensor([-1.3642e-19,  4.5818e-41, -1.3642e-19])
tensor([[-1.3642e-19,  4.5818e-41,  5.1373e-31],
        [ 3.0872e-41,  4.4842e-44,  0.0000e+00]])


### Creating tensors with initial values

In [23]:
x = t.rand(2,3) #Creates a random tensor of size 2 by 3
print(x)

x = t.ones(2,3) #Creates a tensor of size 2 by 3 with all values 1
print(x)

x = t.zeros(2,3) #Creates a tensor of size 2 by 3 with all values 0
print(x)

tensor([[0.1510, 0.8332, 0.0018],
        [0.7689, 0.1120, 0.9018]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### PyTorch data types

In [24]:
x = t.rand(2,3) #Default data type is float32
print(x.dtype)

x = t.ones(2,3,dtype=t.int) #Data type is now int32
print(x)

x = t.rand(2,3,dtype=t.double) #Now the precision is doubled 
print(x)

x = t.empty(2,3,dtype=t.float16) #Float16
print(x)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[0.4160, 0.8460, 0.2250],
        [0.0879, 0.9868, 0.2090]], dtype=torch.float64)
tensor([[-1.7400e+02,  2.9594e+01,  8.8812e+01],
        [ 0.0000e+00, -2.6112e+04, -3.7899e-03]], dtype=torch.float16)


### arange() method

In [25]:
x = t.arange(6) #Generates integers from 0 to 6 (not included)
print(x)

x = t.arange(5,10) #Generates integers from 5 to 10 (not included)
print(x)
print(x.dtype) #Default data type - int64

x = t.arange(5, 100, 10, dtype=t.int16) #Generates integers from 5 to 100 (not included) s.t. gap between each pair is 10  
print(x)
print(x.dtype) #Data type is changed to int16

x = t.arange(5, 10, 0.5)
print(x)
print(x.dtype) #Default float - float32

tensor([0, 1, 2, 3, 4, 5])
tensor([5, 6, 7, 8, 9])
torch.int64
tensor([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95], dtype=torch.int16)
torch.int16
tensor([5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000,
        9.5000])
torch.float32


### linspace() method

In [26]:
x = t.linspace(-5, 5, 10) #Generates 10 equally spaced points between -5 and 5
print(x)
print(x.dtype)

tensor([-5.0000, -3.8889, -2.7778, -1.6667, -0.5556,  0.5556,  1.6667,  2.7778,
         3.8889,  5.0000])
torch.float32


### Identity matrix

In [27]:
x = t.eye(3)
print(x)
print(x.dtype)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
torch.float32


### Full method

In [28]:
x = t.full((2,3), 3.5) #Creates a 2 by 3 matrix filled with 3.5
print(x)

tensor([[3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000]])


### Checking the size of a tensor

In [29]:
x = t.rand(2,3,5)
print(x.size())
print(x.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


### Creating a tensor from data (e.g. Python list)

In [30]:
x = t.tensor([1.4, 3.5])
print(x)
print(x.dtype)

x = t.tensor([1.4, 3.5], dtype=t.double)
print(x)
print(x.dtype)

tensor([1.4000, 3.5000])
torch.float32
tensor([1.4000, 3.5000], dtype=torch.float64)
torch.float64


### Basic tensor operations

In [31]:
x = t.rand(2,2)
y = t.rand(2,2)
print(x)
print(y)

#Addition
z = x+y
print(z)

z = t.add(x,y)
print(z)

y.add_(x) #In-placed addition - x is added to y
print(y)

tensor([[0.3509, 0.6429],
        [0.0553, 0.3442]])
tensor([[0.9432, 0.7759],
        [0.0463, 0.0157]])
tensor([[1.2941, 1.4188],
        [0.1015, 0.3599]])
tensor([[1.2941, 1.4188],
        [0.1015, 0.3599]])
tensor([[1.2941, 1.4188],
        [0.1015, 0.3599]])


Similarly, we can do sub(-), mul(*) and div(/) operations on PyTorch tensors.

### Slicing operations

In [32]:
x = t.rand(5,3)
print(x)

print(x[1,1]) #Only a specific element - e.g. [1,1]
print(x[:,0]) #Extract only the first column
print(x[0,:]) #Extract only the first row

print(x[1,1].item()) #Obtain am item value of a specific element

tensor([[0.2650, 0.7087, 0.9383],
        [0.0234, 0.9718, 0.4854],
        [0.2418, 0.3560, 0.0956],
        [0.4362, 0.8490, 0.9294],
        [0.0343, 0.8768, 0.3846]])
tensor(0.9718)
tensor([0.2650, 0.0234, 0.2418, 0.4362, 0.0343])
tensor([0.2650, 0.7087, 0.9383])
0.9718323349952698


### Reshaping tensors

#### view() method

In [33]:
x = t.rand(4,4)
print(x)

y = x.view(16) #Copy elements into a 1D tensor of size 16
print(y)
print(y.size())

y = x.view(-1) #Copy elements into a 1D tensor and its size is automatically decided
print(y.size())

y = x.view(-1,8) #2nd dimension is set to 8, the 1st dimension automatically decided
print(y)
print(y.size())

tensor([[0.0040, 0.0048, 0.5729, 0.2066],
        [0.0286, 0.0138, 0.2127, 0.5505],
        [0.0341, 0.5896, 0.7446, 0.9005],
        [0.3749, 0.8714, 0.0062, 0.9705]])
tensor([0.0040, 0.0048, 0.5729, 0.2066, 0.0286, 0.0138, 0.2127, 0.5505, 0.0341,
        0.5896, 0.7446, 0.9005, 0.3749, 0.8714, 0.0062, 0.9705])
torch.Size([16])
torch.Size([16])
tensor([[0.0040, 0.0048, 0.5729, 0.2066, 0.0286, 0.0138, 0.2127, 0.5505],
        [0.0341, 0.5896, 0.7446, 0.9005, 0.3749, 0.8714, 0.0062, 0.9705]])
torch.Size([2, 8])


#### reshape() method

In [47]:
x = t.arange(10)
print(x)

y = x.reshape(-1,2)
print(y)

z = x.reshape(2,5)
print(z)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


### Converting tensors (numpy and torch)

In [34]:
import numpy as np

#### torch to numpy

In [35]:
a = t.rand(5)
print(a)
print(a.dtype)

b = a.numpy()
print(b)
print(type(b))

a += 1

print(a) # a and b share the same memory (unless GPUs are available in the system),
print(b) # hence, when a changes, b also and vice versa

tensor([0.5943, 0.6751, 0.6130, 0.1697, 0.7036])
torch.float32
[0.59431666 0.6751411  0.61298096 0.16971195 0.7036039 ]
<class 'numpy.ndarray'>
tensor([1.5943, 1.6751, 1.6130, 1.1697, 1.7036])
[1.5943167 1.6751411 1.612981  1.169712  1.703604 ]


#### numpy to torch

In [36]:
a = np.ones(5)
print(a)

b = t.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### requires_grad argument

This argument (requires_grad) tells that this variable's gradient needs to be calculated later. By default, this is False.

In [37]:
x = t.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
