<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Defining-the-network" data-toc-modified-id="Defining-the-network-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Defining the network</a></span></li><li><span><a href="#Creating-an-object-of-MLP-class" data-toc-modified-id="Creating-an-object-of-MLP-class-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Creating an object of MLP class</a></span></li><li><span><a href="#Inputs-and-outputs" data-toc-modified-id="Inputs-and-outputs-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Inputs and outputs</a></span></li><li><span><a href="#Loss,-forward-and-backward-propagation" data-toc-modified-id="Loss,-forward-and-backward-propagation-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Loss, forward and backward propagation</a></span></li><li><span><a href="#Weights-and-biases" data-toc-modified-id="Weights-and-biases-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Weights and biases</a></span><ul class="toc-item"><li><span><a href="#Accessing-weights-and-biases" data-toc-modified-id="Accessing-weights-and-biases-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Accessing weights and biases</a></span></li><li><span><a href="#Accessing-gradients-of-weights-and-biases" data-toc-modified-id="Accessing-gradients-of-weights-and-biases-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Accessing gradients of weights and biases</a></span></li><li><span><a href="#Accessing-all-weights,-biases-and-their-gradients" data-toc-modified-id="Accessing-all-weights,-biases-and-their-gradients-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Accessing all weights, biases and their gradients</a></span></li></ul></li><li><span><a href="#Accessing-modules-of-a-model" data-toc-modified-id="Accessing-modules-of-a-model-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Accessing modules of a model</a></span></li></ul></div>

# Accessing Network's Weights and Biases

## Defining the network

In [126]:
import torch
import torch.nn as nn

class MLP(nn.Module):
    def __init__(self, n_in, n_hid, n_out):
        super(MLP, self).__init__()
        self.hid = nn.Linear(n_in, n_hid)
        self.out = nn.Linear(n_hid, n_out)
        
    def forward(self, x):
        y = self.hid(x)
        y = torch.relu(y)
        y = self.out(y)
        y = torch.sigmoid(y)
        return y

## Creating an object of MLP class

In [127]:
model = MLP(10, 5, 1)

## Inputs and outputs

In [136]:
x = torch.randn(15, 10)
y = torch.randn(15, 1)

## Loss, forward and backward propagation

In [138]:
loss_fn = nn.MSELoss()
y_pred = model(x)
loss = loss_fn(y, y_pred)
loss.backward()

## Weights and biases

In [112]:
print(model)

MLP(
  (hid): Linear(in_features=10, out_features=5, bias=True)
  (out): Linear(in_features=5, out_features=1, bias=True)
)


### Accessing weights and biases

In [117]:
print(model.hid.weight.shape)
print(model.hid.weight)
print(model.hid.bias.shape)
print(model.hid.bias)

torch.Size([5, 10])
Parameter containing:
tensor([[ 0.0772,  0.1115,  0.2453, -0.2856, -0.1755, -0.0405, -0.2644,  0.0694,
         -0.2554, -0.1751],
        [ 0.1848,  0.0577,  0.0074,  0.0808, -0.2299,  0.0984, -0.0533,  0.1617,
          0.1599, -0.1547],
        [ 0.2562,  0.2514,  0.2442, -0.0632,  0.3123,  0.2604,  0.1371,  0.1963,
         -0.2505, -0.2744],
        [-0.1732, -0.1369, -0.2164, -0.0305, -0.0156, -0.0056,  0.1149,  0.2052,
          0.2131, -0.2029],
        [-0.0324, -0.1085,  0.2008, -0.1941,  0.1115,  0.2785, -0.1823,  0.1931,
          0.1863,  0.0555]], requires_grad=True)
torch.Size([5])
Parameter containing:
tensor([ 0.2722,  0.2639, -0.1227, -0.0792, -0.1531], requires_grad=True)


### Accessing gradients of weights and biases

In [141]:
print(model.hid.weight.grad.shape)
print(model.hid.weight.grad)
print(model.hid.bias.grad.shape)
print(model.hid.bias.grad)

torch.Size([5, 10])
tensor([[-0.0165,  0.0043, -0.0809,  0.0440, -0.0375,  0.0081, -0.0557,  0.0249,
          0.0183, -0.0285],
        [ 0.0313, -0.0200, -0.0584, -0.0259,  0.0051,  0.0161, -0.0559, -0.0093,
         -0.0519,  0.0567],
        [-0.0003,  0.0023, -0.0006, -0.0012, -0.0111,  0.0079,  0.0079, -0.0017,
          0.0007,  0.0082],
        [-0.0140,  0.0287, -0.0789, -0.0120, -0.1087,  0.0765, -0.0141, -0.0458,
         -0.0350,  0.1557],
        [ 0.0749,  0.0660,  0.0446, -0.0437, -0.0295,  0.0393, -0.0319, -0.0403,
         -0.0094, -0.0088]])
torch.Size([5])
tensor([0.0956, 0.1423, 0.0175, 0.2700, 0.1607])


### Accessing all weights, biases and their gradients

In [174]:
for child in model.children():
    print("Child: ", child)
    print("Weights:")
    print("--------")
    print("Shape: ", child.weight.shape)
    print(child.weight)
    print("Gradients:")
    print("----------")
    print("Shape: ", child.weight.grad.shape)
    print(child.weight.grad)
    print()

Child:  Linear(in_features=10, out_features=5, bias=True)
Weights:
--------
Shape:  torch.Size([5, 10])
Parameter containing:
tensor([[-0.0651, -0.0124, -0.2652,  0.1167, -0.0986, -0.3076, -0.2795,  0.2564,
         -0.2160, -0.0814],
        [ 0.0998,  0.1296, -0.2813, -0.0334,  0.2842, -0.0727, -0.1477,  0.0113,
         -0.2827,  0.2274],
        [ 0.1767,  0.1580, -0.0590, -0.0563, -0.2724,  0.0004,  0.0864,  0.2630,
          0.0656,  0.2824],
        [ 0.0253, -0.1578,  0.2199,  0.0417, -0.1964,  0.2624, -0.0759,  0.0503,
         -0.0305,  0.1812],
        [ 0.1751,  0.0473,  0.1872, -0.2895,  0.0130,  0.3051, -0.1708, -0.1869,
         -0.1241, -0.2940]], requires_grad=True)
Gradients:
----------
Shape:  torch.Size([5, 10])
tensor([[-0.0165,  0.0043, -0.0809,  0.0440, -0.0375,  0.0081, -0.0557,  0.0249,
          0.0183, -0.0285],
        [ 0.0313, -0.0200, -0.0584, -0.0259,  0.0051,  0.0161, -0.0559, -0.0093,
         -0.0519,  0.0567],
        [-0.0003,  0.0023, -0.0006, -0.0

## Accessing modules of a model

In [154]:
for module in model.modules():
    print(module)

MLP(
  (hid): Linear(in_features=10, out_features=5, bias=True)
  (out): Linear(in_features=5, out_features=1, bias=True)
)
Linear(in_features=10, out_features=5, bias=True)
Linear(in_features=5, out_features=1, bias=True)
