### Import torch as t

In [19]:
import torch as t

### Creating empty tensors

In [20]:
x = t.empty(1) #Empty tensor of size 1 - scalar
print(x)

x = t.empty(3) #Empty tensor of size 3 - vector of size 3
print(x)

x = t.empty(2,3) #Empty 2D tensor of size 2 by 3
print(x) 

tensor([-1.1763e-25])
tensor([-2.3607e-38,  3.0826e-41, -2.3613e-38])
tensor([[-2.2985e-38,  3.0826e-41, -1.1762e-25],
        [ 4.5907e-41,  8.9683e-44,  0.0000e+00]])


### Creating tensors with initial values

In [21]:
x = t.rand(2,3) #Creates a random tensor of size 2 by 3
print(x)

x = t.ones(2,3) #Creates a tensor of size 2 by 3 with all values 1
print(x)

x = t.zeros(2,3) #Creates a tensor of size 2 by 3 with all values 0
print(x)

tensor([[0.1522, 0.3859, 0.5191],
        [0.1139, 0.6673, 0.5228]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### PyTorch data types

In [28]:
x = t.rand(2,3) #Default data type is float32
print(x.dtype)

x = t.ones(2,3,dtype=t.int) #Data type is now int32
print(x)

x = t.rand(2,3,dtype=t.double) #Now the precision is doubled 
print(x)

x = t.empty(2,3,dtype=t.float16) #Float16
print(x)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[0.1080, 0.9232, 0.8764],
        [0.9771, 0.2174, 0.6208]], dtype=torch.float64)
tensor([[-5.0049e-03, -1.4811e-03,         nan],
        [ 0.0000e+00,  3.3438e+00, -1.5080e-05]], dtype=torch.float16)


### Checking the size of a tensor

In [32]:
x = t.rand(2,3,5)
print(x.size())
print(x.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


### Creating a tensor from data (e.g. Python list)

In [36]:
x = t.tensor([1.4, 3.5])
print(x)
print(x.dtype)

x = t.tensor([1.4, 3.5], dtype=t.double)
print(x)
print(x.dtype)

tensor([1.4000, 3.5000])
torch.float32
tensor([1.4000, 3.5000], dtype=torch.float64)
torch.float64


### Basic tensor operations

In [42]:
x = t.rand(2,2)
y = t.rand(2,2)
print(x)
print(y)

#Addition
z = x+y
print(z)

z = t.add(x,y)
print(z)

y.add_(x) #In-placed addition - x is added to y
print(y)

tensor([[0.9374, 0.8134],
        [0.5301, 0.5703]])
tensor([[0.7362, 0.8280],
        [0.2923, 0.6298]])
tensor([[1.6736, 1.6414],
        [0.8223, 1.2002]])
tensor([[1.6736, 1.6414],
        [0.8223, 1.2002]])
tensor([[1.6736, 1.6414],
        [0.8223, 1.2002]])


Similarly, we can do sub(-), mul(*) and div(/) operations on PyTorch tensors.

### Slicing operations

In [49]:
x = t.rand(5,3)
print(x)

print(x[1,1]) #Only a specific element - e.g. [1,1]
print(x[:,0]) #Extract only the first column
print(x[0,:]) #Extract only the first row

print(x[1,1].item()) #Obtain am item value of a specific element

tensor([[0.5219, 0.1002, 0.4350],
        [0.9013, 0.0695, 0.5179],
        [0.0225, 0.1473, 0.3976],
        [0.0699, 0.9965, 0.3450],
        [0.2587, 0.1359, 0.3642]])
tensor(0.0695)
tensor([0.5219, 0.9013, 0.0225, 0.0699, 0.2587])
tensor([0.5219, 0.1002, 0.4350])
0.06949084997177124


### Reshaping tensors

In [60]:
x = t.rand(4,4)
print(x)

y = x.view(16) #Copy elements into a 1D tensor of size 16
print(y)
print(y.size())

y = x.view(-1) #Copy elements into a 1D tensor and its size is automatically decided
print(y.size())

y = x.view(-1,8) #2nd dimension is set to 8, the 1st dimension automatically decided
print(y)
print(y.size())

tensor([[0.1576, 0.8485, 0.5513, 0.6094],
        [0.8194, 0.6101, 0.7642, 0.9968],
        [0.5201, 0.0201, 0.7127, 0.3716],
        [0.4809, 0.4425, 0.5290, 0.9617]])
tensor([0.1576, 0.8485, 0.5513, 0.6094, 0.8194, 0.6101, 0.7642, 0.9968, 0.5201,
        0.0201, 0.7127, 0.3716, 0.4809, 0.4425, 0.5290, 0.9617])
torch.Size([16])
torch.Size([16])
tensor([[0.1576, 0.8485, 0.5513, 0.6094, 0.8194, 0.6101, 0.7642, 0.9968],
        [0.5201, 0.0201, 0.7127, 0.3716, 0.4809, 0.4425, 0.5290, 0.9617]])
torch.Size([2, 8])


### Converting tensors (numpy and torch)

In [61]:
import numpy as np

#### torch to numpy

In [68]:
a = t.rand(5)
print(a)
print(a.dtype)

b = a.numpy()
print(b)
print(type(b))

a += 1

print(a) # a and b share the same memory (unless GPUs are available in the system),
print(b) # hence, when a changes, b also and vice versa

tensor([0.1296, 0.7950, 0.8402, 0.1749, 0.8593])
torch.float32
[0.12956715 0.7949971  0.840175   0.1749335  0.8593148 ]
<class 'numpy.ndarray'>
tensor([1.1296, 1.7950, 1.8402, 1.1749, 1.8593])
[1.1295671 1.7949971 1.8401749 1.1749334 1.8593148]


#### numpy to torch

In [78]:
a = np.ones(5)
print(a)

b = t.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### Perform operations on a GPU

In [88]:
if t.cuda.is_available():
    gpu = t.device("cuda")
    x = t.ones(5, device=gpu) # x is on GPU
    y = t.ones(5)
    y = y.to(gpu) # y is transfered to GPU
    z = x+y   

print(z)
z = z.to("cpu") # z is now on CPU, remember that numpy works only on CPUs
print(z)

tensor([2., 2., 2., 2., 2.], device='cuda:0')
tensor([2., 2., 2., 2., 2.])


### requires_grad argument

This argument (requires_grad) tells that this variable's gradient needs to be calculated later. By default, this is False.

In [90]:
x = t.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
