## Libraries and functions

### Libraries

In [1]:
import torch
import torch.nn as nn
from torch.autograd.variable import Variable

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


### Functions

In [2]:
def underlined_text(text, char = '='):
    length = len(text)
    print(text)
    for i in range(length):
        print(char, end='')
    print()

## Dataset

### Creating the dataset

In [3]:
underlined_text("X")
X = torch.tensor([[i] for i in range(0,10)]).to(device)
print("Shape = ", X.shape)
print(X)
print()
underlined_text("y")
y = torch.tensor([i for i in range(1,10)])
z = torch.tensor([0])
y = torch.cat((y, z), dim=0).to(device)
print(y.shape)
print(y)
print()
underlined_text("Sequence order: (Input => Output)")
for i in range(len(X)):
    print(X[i].item(), '=>', y[i].item())

X
=
Shape =  torch.Size([10, 1])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]], device='cuda:0')

y
=
torch.Size([10])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], device='cuda:0')

Sequence order: (Input => Output)
0 => 1
1 => 2
2 => 3
3 => 4
4 => 5
5 => 6
6 => 7
7 => 8
8 => 9
9 => 0


### Reshaping dataX

Reshaping the dataX into a format [batch_size, seq_len, no_features].

In [4]:
underlined_text("Reshaped X")
X = X.view(X.shape[0], 1, 1) # [batch_size, seq_len, features]
print(X.shape)
print(X)

Reshaped X
torch.Size([10, 1, 1])
tensor([[[0]],

        [[1]],

        [[2]],

        [[3]],

        [[4]],

        [[5]],

        [[6]],

        [[7]],

        [[8]],

        [[9]]], device='cuda:0')


### Normalizing

In [5]:
underlined_text("Normalizing X")
X = X/float(X.shape[0])
print(X.shape)
print(X)

Normalizing X
torch.Size([10, 1, 1])
tensor([[[0.0000]],

        [[0.1000]],

        [[0.2000]],

        [[0.3000]],

        [[0.4000]],

        [[0.5000]],

        [[0.6000]],

        [[0.7000]],

        [[0.8000]],

        [[0.9000]]], device='cuda:0')


## Creating the model

In the default mode (i.e. batch_first = False), the input shape should have the shape [seq_len, batch_size, 
features]. If you want the input shape should be of the shape [batch_size, seq_len, features], set batch_first = True.

seq_len - Number of time steps in each input stream
<br>
features - Number of input features per time-step
<br>
batch_size - Size of the batches (sample size)
<br>
hidden_size - Number of RNN/LSTM blocks
<br>
num_layers - Number of hidden layers (default = 1)
<br>
<br>
<u>Input shapes</u>
<br>
Input's shape = [seq_len, batch_size, features] if batch_first = False
<br>
Input's shape = [batch_size, seq_len, features] if batch_first = True
<br>
Initial hidden layer's shape = [num_layers, batch_size, hidden_size]
<br>
<br>
<u>Hidden layer's shape</u>
<br>
[num_layers, batch_size, hidden_size]
<br>

<u>Output shape</u>
<br>
Hidden layer's shape = [num_layers, batch_size, hidden_size] (Since in an RNN, hidden state also returned as an output)
<br>
Output's shape = [seq_len, batch_size, hidden_size] if batch_first = False
<br>
Output's shape = [batch_size, seq_len, hidden_size] if batch_first = True

### RNNDigit clsss

#### Class definition

In [6]:
class RNNDigit(nn.Module):
    def __init__(self, input_size, hidden_size, batch_size, num_layers, output_size):
        super(RNNDigit, self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.batch_size = batch_size
        self.num_layers = num_layers
        self.output_size = output_size
        
        self.rnn_layer = nn.RNN(input_size=self.input_size, hidden_size=self.hidden_size,
                               num_layers=self.num_layers, batch_first=True, dropout=0.3)
        
        self.linear_layer = nn.Linear(in_features=self.hidden_size, out_features=10)
        
        # Uncomment if needed to initialize hidden and cell states with random values
        # self.hidden = self.init_hidden().to(device) # Initializing the hidden state
    
    def init_hidden(self):
        # Use this method, if needed to initialize the hidden states and cell states with random values
        hidden_0 = Variable(torch.zeros(self.num_layers, self.batch_size, self.hidden_size))
        return hidden_0
        
    def forward(self, x):
        rnn_out, self.hidden = self.rnn_layer(x, None) # None says zero initial hidden and cell states
        reshaped_rnn_out = rnn_out.view(self.batch_size, self.hidden_size)
        final_out = self.linear_layer(reshaped_rnn_out)
        return final_out
        
rnn = RNNDigit(input_size=1, hidden_size=32, batch_size=10, num_layers=2, output_size=10).to(device)
print(rnn)

RNNDigit(
  (rnn_layer): RNN(1, 32, num_layers=2, batch_first=True, dropout=0.3)
  (linear_layer): Linear(in_features=32, out_features=10, bias=True)
)


#### Loss function and optimizer

In [7]:
import torch.optim as optim

loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(rnn.parameters())

#### Model evaluation

In [8]:
def model_eval(preds, outputs):
    total = 0
    correct = 0
    
    max_vals, pred_class = torch.max(preds, dim=1)
    for i in range(10):
        if (pred_class[i]==outputs[i]):
            correct += 1
    acc = (correct/10.0)*100.0
    return acc

#### Training loop

In the loss.backward() function, the parameter 'retain_graph' needs to be set as 'True', since part of the computational graph will be freed during the execution of the loop. This is not needed in most cases, however, in an RNN, previous hidden states are passed to RNN cells, hence it needs the full graph to calculate the derivatives.

In [9]:
underlined_text("Training loop")
epochs = 5000

for epoch in range(epochs):
    optimizer.zero_grad()
    y_pred = rnn(X)
    loss = loss_fn(y_pred, y)
    accuracy = model_eval(y_pred, y)
    loss.backward(retain_graph=True)
    optimizer.step()
    if ((epoch+1)%100 == 0):
        print("Epoch: ", "{:4d}/{:4d} ==>".format(epoch+1,epochs), 
              "Loss: ", "{:6.4f}, ".format(loss.item()), "Accuracy: ", "{:6.2f}%".format(accuracy))

Training loop
Epoch:   100/5000 ==> Loss:  2.0938,  Accuracy:   20.00%
Epoch:   200/5000 ==> Loss:  1.5306,  Accuracy:   40.00%
Epoch:   300/5000 ==> Loss:  1.2720,  Accuracy:   50.00%
Epoch:   400/5000 ==> Loss:  1.0482,  Accuracy:   80.00%
Epoch:   500/5000 ==> Loss:  0.9512,  Accuracy:   70.00%
Epoch:   600/5000 ==> Loss:  0.8325,  Accuracy:   80.00%
Epoch:   700/5000 ==> Loss:  0.7561,  Accuracy:  100.00%
Epoch:   800/5000 ==> Loss:  0.6593,  Accuracy:   80.00%
Epoch:   900/5000 ==> Loss:  0.6652,  Accuracy:   80.00%
Epoch:  1000/5000 ==> Loss:  0.6071,  Accuracy:   80.00%
Epoch:  1100/5000 ==> Loss:  0.5166,  Accuracy:   80.00%
Epoch:  1200/5000 ==> Loss:  0.4802,  Accuracy:  100.00%
Epoch:  1300/5000 ==> Loss:  0.4399,  Accuracy:   90.00%
Epoch:  1400/5000 ==> Loss:  0.3263,  Accuracy:  100.00%
Epoch:  1500/5000 ==> Loss:  0.3339,  Accuracy:  100.00%
Epoch:  1600/5000 ==> Loss:  0.2539,  Accuracy:  100.00%
Epoch:  1700/5000 ==> Loss:  0.3066,  Accuracy:  100.00%
Epoch:  1800/5000